// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDevLoop.Infrastructure.Persistence;

#nullable disable

namespace WebDevLoop.Infrastructure.Persistence.Migrations;

[DbContext(typeof(WebDevLoopDbContext))]
[Migration("20261009123742_OutboxDeadLetter")]
partial class _20261009123742_OutboxDeadLetter
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128");

        modelBuilder.Entity("WebDevLoop.Core.Domain.FindingIssuance", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Axis")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("CreatedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("Fingerprint")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long?>("IssueDatabaseId")
                    .HasColumnType("INTEGER");

                b.Property<int?>("IssueNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("SourceStepRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("SpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("UpdatedAt")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("SourceStepRunId")
                    .HasDatabaseName("IX_FindingIssuances_SourceStep");

                b.HasIndex("SpecRunId", "Fingerprint")
                    .IsUnique()
                    .HasDatabaseName("UX_FindingIssuances_SpecRun_Fingerprint");

                b.ToTable("FindingIssuances");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.IntegrationSaga", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Checkpoint")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("CreatedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("ExpectedPriorIntegrationSha")
                    .HasColumnType("TEXT");

                b.Property<string>("ExternalIdempotencyKey")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("LastError")
                    .HasColumnType("TEXT");

                b.Property<int?>("PullRequestNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("SpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("SquashCommitSha")
                    .HasColumnType("TEXT");

                b.Property<string>("StackBranchName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int?>("StackNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("TicketRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("UpdatedAt")
                    .HasColumnType("INTEGER");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("SpecRunId");

                b.HasIndex("TicketRunId")
                    .IsUnique()
                    .HasDatabaseName("UX_IntegrationSagas_IncompletePerTicket")
                    .HasFilter("\"Checkpoint\" <> 'Completed'");

                b.ToTable("IntegrationSagas");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.OutboxMessage", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Attempts")
                    .HasColumnType("INTEGER");

                b.Property<long>("CreatedAt")
                    .HasColumnType("INTEGER");

                b.Property<long?>("DeadLetteredAt")
                    .HasColumnType("INTEGER");

                b.Property<long?>("DispatchedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("LastError")
                    .HasColumnType("TEXT");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("DispatchedAt")
                    .HasDatabaseName("IX_OutboxMessages_Pending")
                    .HasFilter("\"DispatchedAt\" IS NULL AND \"DeadLetteredAt\" IS NULL");

                b.ToTable("OutboxMessages");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.PullStackLayer", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("BaseBranch")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("BranchName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("CommitSha")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("CreatedAt")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsDraft")
                    .HasColumnType("INTEGER");

                b.Property<int>("Position")
                    .HasColumnType("INTEGER");

                b.Property<int>("PullRequestNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("SpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int?>("StackNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("TicketRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("UpdatedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("VerifiedDiffSha")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("TicketRunId");

                b.HasIndex("SpecRunId", "Position")
                    .IsUnique()
                    .HasDatabaseName("UX_PullStackLayers_SpecRun_Position");

                b.ToTable("PullStackLayers");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.RepositoryRecord", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CloneUrl")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("CreatedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("DefaultBaseBranch")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("INTEGER");

                b.Property<string>("LocalPath")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<string>("Owner")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .UseCollation("NOCASE");

                b.Property<long>("UpdatedAt")
                    .HasColumnType("INTEGER");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Owner", "Name")
                    .IsUnique()
                    .HasDatabaseName("UX_Repositories_Owner_Name");

                b.ToTable("Repositories");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.RunEvent", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<long>("OccurredAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("SpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("TicketRunId")
                    .HasColumnType("TEXT");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SpecRunId")
                    .HasDatabaseName("IX_RunEvents_SpecRun");

                b.HasIndex("TicketRunId");

                b.ToTable("RunEvents");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.SettingsProfile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("BaseBranch")
                    .HasColumnType("TEXT");

                b.Property<string>("CopilotBaseDirectory")
                    .HasColumnType("TEXT");

                b.Property<int?>("MaxActiveSpecsPerRepo")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MaxConcurrentImplementersGlobal")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MaxConcurrentImplementersPerRepo")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MaxRetries")
                    .HasColumnType("INTEGER");

                b.Property<int?>("MaxReviewIterations")
                    .HasColumnType("INTEGER");

                b.Property<int?>("ParentReviewCycleLimit")
                    .HasColumnType("INTEGER");

                b.Property<bool?>("PatFallbackEnabled")
                    .HasColumnType("INTEGER");

                b.Property<int?>("RepositoryId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ScopeKey")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("INTEGER")
                    .HasComputedColumnSql("COALESCE(\"RepositoryId\", 0)", true);

                b.Property<string>("SpecDependencyMode")
                    .HasColumnType("TEXT");

                b.Property<int?>("TesterCycleLimit")
                    .HasColumnType("INTEGER");

                b.Property<string>("TesterRunInstructions")
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.Property<string>("WorkspaceRootDirectory")
                    .HasColumnType("TEXT");

                b.Property<string>("_roles")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("RolesJson");

                b.ComplexProperty(typeof(Dictionary<string, object>), "TestPortRange", "WebDevLoop.Core.Domain.SettingsProfile.TestPortRange#TestPortRange", b1 =>
                    {
                        b1.Property<int>("End")
                            .HasColumnType("INTEGER");

                        b1.Property<int>("Start")
                            .HasColumnType("INTEGER");
                    });

                b.HasKey("Id");

                b.HasIndex("RepositoryId");

                b.HasIndex("ScopeKey")
                    .IsUnique()
                    .HasDatabaseName("UX_SettingsProfiles_Scope");

                b.ToTable("SettingsProfiles");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.SpecDependency", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("BlockedSpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("BlockingSpecRunId")
                    .HasColumnType("TEXT");

                b.Property<string>("ModeAtStart")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Source")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.ComplexProperty(typeof(Dictionary<string, object>), "ExternalBlockingIssue", "WebDevLoop.Core.Domain.SpecDependency.ExternalBlockingIssue#IssueRef", b1 =>
                    {
                        b1.Property<long?>("DatabaseId")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("NodeId")
                            .HasColumnType("TEXT");

                        b1.Property<int>("Number")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("Owner")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.Property<string>("Repo")
                            .IsRequired()
                            .HasColumnType("TEXT");
                    });

                b.HasKey("Id");

                b.HasIndex("BlockingSpecRunId");

                b.HasIndex("BlockedSpecRunId", "BlockingSpecRunId")
                    .IsUnique()
                    .HasDatabaseName("UX_SpecDependencies_Blocked_Blocking")
                    .HasFilter("\"BlockingSpecRunId\" IS NOT NULL");

                b.ToTable("SpecDependencies");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.SpecRun", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("BaseBranch")
                    .HasColumnType("TEXT");

                b.Property<string>("BodySnapshot")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long?>("CompletedAt")
                    .HasColumnType("INTEGER");

                b.Property<long>("CreatedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("DependencyModeUsed")
                    .HasColumnType("TEXT");

                b.Property<string>("FailureReason")
                    .HasColumnType("TEXT");

                b.Property<string>("IntegrationBaseSha")
                    .HasColumnType("TEXT");

                b.Property<string>("IntegrationBranch")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("IntegrationTipSha")
                    .HasColumnType("TEXT");

                b.Property<int?>("MaxActiveSpecsSlot")
                    .HasColumnType("INTEGER");

                b.Property<int>("QueuePosition")
                    .HasColumnType("INTEGER");

                b.Property<long?>("ReadyAt")
                    .HasColumnType("INTEGER");

                b.Property<int>("RepositoryId")
                    .HasColumnType("INTEGER");

                b.Property<int>("ReviewCycle")
                    .HasColumnType("INTEGER");

                b.Property<long?>("StartedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("TestCycle")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.ComplexProperty(typeof(Dictionary<string, object>), "ParentIssue", "WebDevLoop.Core.Domain.SpecRun.ParentIssue#IssueRef", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<long?>("DatabaseId")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("NodeId")
                            .HasColumnType("TEXT");

                        b1.Property<int>("Number")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("Owner")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.Property<string>("Repo")
                            .IsRequired()
                            .HasColumnType("TEXT");
                    });

                b.HasKey("Id");

                b.HasIndex("Status")
                    .HasDatabaseName("IX_SpecRuns_Status");

                b.HasIndex("RepositoryId", "MaxActiveSpecsSlot")
                    .IsUnique()
                    .HasDatabaseName("UX_SpecRuns_ActiveSlotPerRepository")
                    .HasFilter("\"Status\" IN ('Preparing', 'Running', 'ParentReviewing', 'Testing', 'ReadyForReview', 'AwaitingMerge')");

                b.HasIndex("RepositoryId", "QueuePosition")
                    .HasDatabaseName("IX_SpecRuns_Repository_QueuePosition");

                b.ToTable("SpecRuns");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.StepRun", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<string>("AgentRole")
                    .HasColumnType("TEXT");

                b.Property<int>("Attempt")
                    .HasColumnType("INTEGER");

                b.Property<string>("BranchName")
                    .HasColumnType("TEXT");

                b.Property<long?>("CompletedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("CopilotSessionId")
                    .HasColumnType("TEXT");

                b.Property<string>("FailureReason")
                    .HasColumnType("TEXT");

                b.Property<string>("InputPromptHash")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("SpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long?>("StartedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("StructuredResultJson")
                    .HasColumnType("TEXT");

                b.Property<string>("TicketRunId")
                    .HasColumnType("TEXT");

                b.Property<long?>("TimeoutAt")
                    .HasColumnType("INTEGER");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.Property<string>("WorktreePath")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SpecRunId")
                    .HasDatabaseName("IX_StepRuns_SpecRun");

                b.HasIndex("Status")
                    .HasDatabaseName("IX_StepRuns_Status");

                b.HasIndex("TicketRunId")
                    .IsUnique()
                    .HasDatabaseName("UX_StepRuns_ActiveImplementOrFixPerTicket")
                    .HasFilter("\"Kind\" IN ('Implement', 'Fix') AND \"Status\" IN ('Pending', 'Running')");

                b.HasIndex("SpecRunId", "Kind")
                    .IsUnique()
                    .HasDatabaseName("UX_StepRuns_ActiveAppOwnedKindPerRun")
                    .HasFilter("\"AgentRole\" IS NULL AND \"Status\" IN ('Pending', 'Running')");

                b.ToTable("StepRuns");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.TestLease", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<long>("AcquiredAt")
                    .HasColumnType("INTEGER");

                b.Property<long>("ExpiresAt")
                    .HasColumnType("INTEGER");

                b.Property<int>("Port")
                    .HasColumnType("INTEGER");

                b.Property<int?>("ProcessId")
                    .HasColumnType("INTEGER");

                b.Property<long?>("ReleasedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("SpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.Property<string>("WorkspacePath")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Port")
                    .IsUnique()
                    .HasDatabaseName("UX_TestLeases_ActivePort")
                    .HasFilter("\"ReleasedAt\" IS NULL");

                b.HasIndex("SpecRunId")
                    .IsUnique()
                    .HasDatabaseName("UX_TestLeases_ActivePerRun")
                    .HasFilter("\"ReleasedAt\" IS NULL");

                b.ToTable("TestLeases");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.TicketDependency", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("BlockedTicketRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("BlockingTicketRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Source")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("SpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("BlockingTicketRunId");

                b.HasIndex("SpecRunId")
                    .HasDatabaseName("IX_TicketDependencies_SpecRun");

                b.HasIndex("BlockedTicketRunId", "BlockingTicketRunId")
                    .IsUnique()
                    .HasDatabaseName("UX_TicketDependencies_Blocked_Blocking");

                b.ToTable("TicketDependencies");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.TicketRun", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");

                b.Property<int>("Attempt")
                    .HasColumnType("INTEGER");

                b.Property<string>("BodySnapshot")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("BranchName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("CreatedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("FailureReason")
                    .HasColumnType("TEXT");

                b.Property<string>("IntegratedCommitSha")
                    .HasColumnType("TEXT");

                b.Property<string>("LastImplementedSha")
                    .HasColumnType("TEXT");

                b.Property<int?>("PullRequestNumber")
                    .HasColumnType("INTEGER");

                b.Property<int>("ReviewIteration")
                    .HasColumnType("INTEGER");

                b.Property<string>("SpecRunId")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int?>("StackPosition")
                    .HasColumnType("INTEGER");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("UpdatedAt")
                    .HasColumnType("INTEGER");

                b.Property<int>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.Property<string>("WorktreePath")
                    .HasColumnType("TEXT");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Issue", "WebDevLoop.Core.Domain.TicketRun.Issue#IssueRef", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<long?>("DatabaseId")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("NodeId")
                            .HasColumnType("TEXT");

                        b1.Property<int>("Number")
                            .HasColumnType("INTEGER");

                        b1.Property<string>("Owner")
                            .IsRequired()
                            .HasColumnType("TEXT");

                        b1.Property<string>("Repo")
                            .IsRequired()
                            .HasColumnType("TEXT");
                    });

                b.HasKey("Id");

                b.HasIndex("SpecRunId", "Status")
                    .HasDatabaseName("IX_TicketRuns_SpecRun_Status");

                b.ToTable("TicketRuns");
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.FindingIssuance", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.StepRun", null)
                    .WithMany()
                    .HasForeignKey("SourceStepRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("SpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.IntegrationSaga", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("SpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WebDevLoop.Core.Domain.TicketRun", null)
                    .WithMany()
                    .HasForeignKey("TicketRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.PullStackLayer", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("SpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WebDevLoop.Core.Domain.TicketRun", null)
                    .WithMany()
                    .HasForeignKey("TicketRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.RunEvent", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("SpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WebDevLoop.Core.Domain.TicketRun", null)
                    .WithMany()
                    .HasForeignKey("TicketRunId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.SettingsProfile", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.RepositoryRecord", null)
                    .WithMany()
                    .HasForeignKey("RepositoryId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.SpecDependency", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("BlockedSpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("BlockingSpecRunId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.SpecRun", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.RepositoryRecord", null)
                    .WithMany()
                    .HasForeignKey("RepositoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.StepRun", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("SpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WebDevLoop.Core.Domain.TicketRun", null)
                    .WithMany()
                    .HasForeignKey("TicketRunId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.TestLease", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("SpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.TicketDependency", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.TicketRun", null)
                    .WithMany()
                    .HasForeignKey("BlockedTicketRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WebDevLoop.Core.Domain.TicketRun", null)
                    .WithMany()
                    .HasForeignKey("BlockingTicketRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("SpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

        modelBuilder.Entity("WebDevLoop.Core.Domain.TicketRun", b =>
            {
                b.HasOne("WebDevLoop.Core.Domain.SpecRun", null)
                    .WithMany()
                    .HasForeignKey("SpecRunId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
